FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod ./

COPY go.sum* ./

RUN go mod download

COPY . .

RUN go mod tidy

RUN CGO_ENABLED=0 GOOS=linux go build -o my-app-multistage main.go


FROM alpine:3.18

WORKDIR /root/

COPY --from=builder /app/my-app-multistage .

CMD ["./my-app-multistage"]