version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile.light
      args:
        - GO_IMAGE=${GO_VERSION}
    container_name: go-backend
    environment:
      - REDIS_URL=redis:${REDIS_PORT} 
      - APP_MODE=${APP_ENV}
    networks:
      - frontend
      - backend
    depends_on:
      redis:
        condition: service_healthy # Чекаємо, поки база скаже "я ок"
  
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ${CERT_PATH}:/etc/nginx/ssl/server.crt:ro # сертификат
      - ${KEY_PATH}:/etc/nginx/ssl/server.key:ro # ключ
    networks:
      - frontend
    depends_on:
      - go-app

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-db
    command: redis-server --port ${REDIS_PORT}
    volumes:
      - redis-data:/data
    networks:
      - backend # База НЕ бачить frontend мережу
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus:${PROM_VERSION}
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports: [] # Видаляємо зовнішні порти
    networks:
      - monitoring
      - backend

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports: []
    environment:
       - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
       - GF_SERVER_ROOT_URL=https://${DOMAIN}/grafana/
       - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - monitoring
      - frontend

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports: [] 
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0 # Конкретна версія
    container_name: cadvisor
    privileged: true # Дає cAdvisor права читати системні дані
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro # Додай це
      - /etc/machine-id:/etc/machine-id:ro
    ports: []
    networks:
      - monitoring



volumes:
  redis-data:

networks:
  frontend: # Мережа для Nginx та Go
  backend: # Мережа для Go та Redis
  monitoring:  # Мережа для метрик