events {}

http {

    charset utf-8;

    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

        server {
        listen 443 ssl;
        server_name localhost;

        # Шляхи до сертифікатів всередині контейнера
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;
        

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /api/ {
            proxy_pass http://go-app:8080/api/; # Звертаємося до сервісу за іменем з Compose
            proxy_set_header Host $host;
            #proxy_set_header X-Real-IP $remote_addr;
        }
        location /grafana/ {
            
            proxy_pass http://grafana:3000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $host;

            # Переписуємо редиректи, які Grafana може надсилати без домену
            proxy_redirect http://grafana:3000/ /grafana/;
            # Або спробуй з доменом (якщо перше не допоможе):
            # proxy_redirect http://localhost:3000/ https://localhost/grafana/;

        }
    }
}
